// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class FulltextsearchService {
    /**
 * @returns unknown OK
 * @throws ApiError
 */
    public static postUmbracoFulltextsearchApiV5FulltextsearchReindexnodes(data: $OpenApiTs['/umbraco/fulltextsearch/api/v5/fulltextsearch/reindexnodes']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/fulltextsearch/api/v5/fulltextsearch/reindexnodes']['post']['res'][200]> {
        const { requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/fulltextsearch/api/v5/fulltextsearch/reindexnodes',
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}