// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:37830/' | (string & {});
};

export type ReIndexRequest = {
    nodeKey?: null | string;
    includeDescendants: boolean;
};

export type ReIndexResult = {
    success: boolean;
    message?: null | string;
};

export type PostFulltextsearchIndexReindexnodesData = {
    body: ReIndexRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v5/fulltextsearch/index/reindexnodes';
};

export type PostFulltextsearchIndexReindexnodesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostFulltextsearchIndexReindexnodesResponses = {
    /**
     * OK
     */
    200: ReIndexResult;
};

export type PostFulltextsearchIndexReindexnodesResponse = PostFulltextsearchIndexReindexnodesResponses[keyof PostFulltextsearchIndexReindexnodesResponses];
