// This file is auto-generated by @hey-api/openapi-ts


export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ReIndexRequest = {
    nodeKey?: string | null;
    includeDescendants: boolean;
};

export type ReIndexResult = {
    success: boolean;
    message?: string | null;
};

export type $OpenApiTs = {
    '/umbraco/fulltextsearch/api/v5/fulltextsearch/reindexnodes': {
        post: {
            req: {
                requestBody?: ReIndexRequest;
            };
            res: {
                /**
 * OK
 */
                200: ReIndexResult;
            };
        };
    };
};