// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:37830' | (string & {});
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ReIndexRequest = {
    nodeKey?: string | null;
    includeDescendants: boolean;
};

export type ReIndexResult = {
    success: boolean;
    message?: string | null;
};

export type PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesData = {
    body?: ReIndexRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v5/fulltextsearch/index/reindexnodes';
};

export type PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesResponses = {
    /**
     * OK
     */
    200: ReIndexResult;
};

export type PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesResponse = PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesResponses[keyof PostUmbracoManagementApiV5FulltextsearchIndexReindexnodesResponses];
