export default {
    fullTextSearch: {
        indexStatus: 'Statws Mynegai',
        indexableNodes: 'Nodau Mynegeiddadwy',
        indexableNodesDescription: 'Cyfanswm y nodau y gellir eu mynegeio, yn ôl y ffurfweddiad Full Text Search presennol',
        allIndexableNodesAreIndexed: 'Mae gan bob nod a ellir ei mynegeio gynnwys testun llawn yn yr mynegai',
        indexedNodes: 'Nodau Mynegeiedig',
        indexedNodesDescription: 'Cyfanswm y nodau mynegeiedig y gellir eu chwilio gyda Full Text Search',
        missingNodes: 'Nodau ar Goll',
        missingNodesDescription: 'Cyfanswm y nodau mynegeiedig sydd ar goll, yn ôl y ffurfweddiad Full Text Search presennol',
        couldntGetMissingNodes: 'Methwyd â chael nodau coll',
        nodesAreMissingInIndex: 'Mae {0} nod(au) yn methu eu cynnwys testun llawn yn yr mynegai',
        incorrectIndexedNodes: 'Nodau sydd wedi\'u Mynegeio yn Anghywir',
        incorrectIndexedNodesDescription: 'Cyfanswm y nodau mynegeiedig na ddylai fod wedi\'u mynegeio yn ôl y ffurfweddiad Full Text Search presennol',
        couldntGetIncorrectIndexedNodes: 'Methu â chael nodau wedi\'u mynegeio\' yn anghywir',
        nodesAreIncorrectlyIndexed: 'Mae {0} nod(au) wedi\'u mynegeio\'n anghywir gyda chynnwys testun llawn',
        reindexNodes: 'Ail-fynegi Nodau',
        reindexedNodes: 'Mae {0} nod(au) wedi\'u hail-fynegeio',
        reindexing: 'Ail-fynegio...',
        reindex: 'Ail-fynegi',
        reindexDescription: 'Dewiswch a ydych am ail-fynegi pob nod ai peidio',
        reindexWithDescendants: 'Ail-fynegi gyda disgynyddion',
        includeDescendants: 'Cynnwys disgynyddion',
        allNodes: 'Pob nod',
        selectNodes: 'Dewis nodau',
        selectNodesDescription: 'Dewiswch y nodau i\'w hail-fynegi',
        selectedNodes: 'Nodau a ddewiswyd',
        description: 'Disgrifiad',
        developedBy: 'Datblygwyd gan',
        sponsoredBy: 'Noddwyd gan',
        status: 'Statws',
        search: 'Chwilio',
        enterKeywordsHere: 'Rhowch eiriau allweddol yma',
        advancedSettings: 'Gosodiadau Uwch',
        inspect: 'Archwilio',
        searchType: 'Math o chwiliad',
        searchTypeDescription: 'Y math o chwiliad i\'w wneud.',
        titleProperties: 'Priodweddau teitl',
        titlePropertiesDescription: 'Ychwanegwch enwau maes i\'w defnyddio ar gyfer priodweddau teitl. Sylwer, fod hyn yn diystyru\'r gosodiad ffurfweddiad, felly bydd angen ychwanegu pob maes rydych am eu defnyddio ar gyfer teitlau yma.',
        titleBoost: 'Hyby teitl',
        titleBoostDescription: 'Gosodwch y gwerth hyby ar gyfer y priodweddau teitl, i wneud teitlau\'n bwysicach na thestun y corff wrth chwilio.',
        bodyProperties: 'Priodweddau\'r corff',
        bodyPropertiesDescription: 'Ychwanegwch enwau maes i\'w defnyddio ar gyfer priodweddau\'r corff. Sylwer, fod hyn yn diystyru\'r gosodiad ffurfweddiad, felly bydd angen ychwanegu pob maes rydych am eu defnyddio ar gyfer testun y corff yma.',
        summaryProperties: 'Priodoleddau Crynodeb',
        summaryPropertiesDescription: 'Ychwanegwch enwau maes i\'w defnyddio ar gyfer priodweddau crynodeb. Sylwer, os nad ydych yn nodi unrhyw briodweddau crynodeb, bydd y priodweddau corff yn cael eu defnyddio yn lle.',
        summaryLength: 'Hyd y Crynodeb',
        summaryLengthDescription: 'Gosodwch hyd y crynodeb yn y canlyniadau. Y diofyn yw 300 o gymeriadau.',
        rootNodes: 'Nodau gwraidd',
        rootNodesDescription: 'Gyda\'r gosodiad hwn, gallwch gyfyngu\'r canlyniadau chwilio i fod yn ddisgynyddion y nodau a ddewiswyd.',
        culture: 'Diwylliant',
        cultureDescription: 'Defnyddir hwn i ddiffinio pa ddiwylliant i chwilio ynddo. Mae\'n debyg y dylech osod hwn bob amser, ond gallai weithio hebddo, mewn safleoedd un iaith.',
        enableWildcards: 'Galluogi cardiau gwyllt',
        enableWildcardsDescription: 'Mae hyn yn galluogi neu\'n analluogi defnydd o gardiau gwyllt yn y termau chwilio. Mae nodau cerdyn gwyllt yn cael eu hychwanegu\'n awtomatig at bob un o\'r termau.',
        fuzzyness: 'Aneglurder',
        fuzzynessDescription: 'Defnyddir aneglurder i gyfateb eich term chwilio gyda geiriau tebyg. Mae\'r dull hwn yn gosod y paramedr aneglurder y chwiliad. Y rhagosodiad yw 0.8. Os yw cardiau gwyllt yn cael eu galluogi, ni ddefnyddir aneglurder.',
        allowedContentTypes: 'Mathau o Gynnwys a ganiateir',
        allowedContentTypesDescription: 'Cyfyngu\'r chwiliad i nodau efo enwau arall fathau o gynnwys penodedig.',
        fullTextSearchIsDisabled: 'Mae FullTextSearch wedi\'i analluogi',
        fullTextSearchIsEnabled: 'Mae FullTextSearch wedi\'i alluogi',
        externalIndexNotFound: 'Heb ddod o hyd i ExternalIndex',
        enabled: 'Wedi\'i alluogi',
        defaultTitleField: 'Maes Teitl diofyn',
        indexingActiveKey: 'Allwedd "Indexing Active"',
        disallowedContentTypeAliases: 'Enwau arall y mathau o gynnwys na caniateir',
        disallowedPropertyAliases: 'Enwau arall y Eiddo na caniateir',
        xPathsToRemove: 'Llwybrau XPath i\'w tynnu o\'r cynnwys',
        fullTextContentField: 'Maes Cynnwys Testun Llawn',
        fullTextPathField: 'Maes Llwybr Testun Llawn'
    }
};
