export default {
    fullTextSearch: {
        indexStatus: 'Index Status',
        indexableNodes: 'Indekserbare noder',
        indexableNodesDescription: 'Antal noder der kan indekseres, ifølge den nuværende konfiguration',
        allIndexableNodesAreIndexed: 'Alle indekserbare noder har full text indhold i indekset',
        indexedNodes: 'Indekserede noder',
        indexedNodesDescription: 'Antal noder der kan søges frem med Full Text Search',
        missingNodes: 'Manglende noder',
        missingNodesDescription: 'Antal noder der mangler full text indhold i indekset',
        couldntGetMissingNodes: 'Kunne ikke hente manglende noder',
        nodesAreMissingInIndex: '{0} node(r) mangler full text indhold i indekset',
        incorrectIndexedNodes: 'Fejlagtigt indekserede noder',
        incorrectIndexedNodesDescription: 'Antal noder der ikke burde være indekseret, ifølge den nuværende konfiguration',
        couldntGetIncorrectIndexedNodes: 'Kunne ikke hente fejlagtigt indekserede noder',
        nodesAreIncorrectlyIndexed: '{0} node(r) er fejlagtigt indekseret med full text indhold',
        reindexNodes: 'Reindeksér noder',
        reindexedNodes: 'Reindekserede {0} node(r)',
        reindexing: 'Reindekserer...',
        reindex: 'Reindeksér',
        reindexDescription: 'Vælg om alle noder skal reindekseres',
        reindexWithDescendants: 'Reindeksér med undernoder',
        includeDescendants: 'Inkludér undernoder',
        allNodes: 'Alle noder',
        selectNodes: 'Vælg noder',
        selectNodesDescription: 'Vælg noder at reindeksere',
        selectedNodes: 'Valgte noder',
        description: 'Beskrivelse',
        developedBy: 'Udviklet af',
        sponsoredBy: 'Sponsoreret af',
        status: 'Status',
        search: 'Søg',
        enterKeywordsHere: 'Indtast søgeord her',
        advancedSettings: 'Avancerede indstillinger',
        inspect: 'Inspicér',
        searchType: 'Søgningstype',
        searchTypeDescription: 'Hvilken slags søgning skal der foretages',
        titleProperties: 'Titelfelter',
        titlePropertiesDescription: 'Vælg felter der skal bruges til titlen for søgeresultatet. Bemærk, dette overskriver standardkonfigurationen, vælg derfor alle ønskede felter her.',
        titleBoost: 'Titelboost',
        titleBoostDescription: 'Sæt boost værdien for titelfelterne, så titler vægter højere end indhold i søgningen.',
        bodyProperties: 'Indholdsfelter',
        bodyPropertiesDescription: 'Vælg felter der skal bruges til indholdet for søgeresultatet. Bemærk, dette overskriver standardkonfigurationen, vælg derfor alle ønskede felter her.',
        summaryProperties: 'Beskrivelsesfelter',
        summaryPropertiesDescription: 'Vælg felter der skal bruges til beskrivelsen af søgeresultatet. Bemærk, dette overskriver standardkonfigurationen, vælg derfor alle ønskede felter her.',
        summaryLength: 'Beskrivelseslængde',
        summaryLengthDescription: 'Angiv beskrivelseslængden for søgeresultaterne. Standardindstillingen er 300 tegn.',
        rootNodes: 'Rodnoder',
        rootNodesDescription: 'Med denne indstilling, kan du begrænse søgeresultaterne, til at være undernoder til den/de valgte noder.',
        culture: 'Sprog',
        cultureDescription: 'Vælg hvilket sprog der skal søges på. Du bør altid vælge dette, men søgningen virker muligvis uden sprog, hvis dit site ikke er sprogvarieret.',
        enableWildcards: 'Aktiver wildcards',
        enableWildcardsDescription: 'Dette aktiverer wildcards i søgningen, wildcard tegnet tilføjes automatisk til hver søgeterm.',
        fuzzyness: 'Fuzzyness',
        fuzzynessDescription: 'Fuzzyness bruges til at matche en søgeterm med lignende termer. Standardindstillingen er 0.8. Hvis wildcards er aktiveret, vil fuzzyness ikke blive brugt.',
        allowedContentTypes: 'Tilladte dokumenttyper',
        allowedContentTypesDescription: 'Begrænser søgningen til indhold af de valgte dokumenttypealiaser.',
        externalIndexNotFound: 'ExternalIndex blev ikke fundet',
        fullTextSearchIsDisabled: 'FullTextSearch er deaktiveret',
        fullTextSearchIsEnabled: 'FullTextSearch is aktiveret',
        enabled: 'Aktiveret',
        defaultTitleField: 'Standard titel felt',
        indexingActiveKey: '"Aktiv indeksering" nøgle',
        disallowedContentTypeAliases: 'Udelukkede dokumenttype aliaser',
        disallowedPropertyAliases: 'Udelukkede egenskabsaliaser',
        xPathsToRemove: 'Fjern XPaths fra indhold',
        fullTextContentField: 'Full Text indholdsfelt',
        fullTextPathField: 'Full Text sti felt'
    }
};
