export default {
    fullTextSearch: {
        indexStatus: 'Index Status',
        indexableNodes: 'Indexable Nodes',
        indexableNodesDescription: 'The total number of indexable nodes, according to the current Full Text Search config',
        allIndexableNodesAreIndexed: 'All indexable nodes has full text content in index',
        indexedNodes: 'Indexed Nodes',
        indexedNodesDescription: 'The total number of indexed nodes searchable by Full Text Search',
        missingNodes: 'Missing Nodes',
        missingNodesDescription: 'The total number of missing indexed nodes, according to the current Full Text Search config',
        couldntGetMissingNodes: "Couldn't get missing nodes",
        nodesAreMissingInIndex: '{0} node(s) are missing full text content in index',
        incorrectIndexedNodes: 'Incorrectly Indexed Nodes',
        incorrectIndexedNodesDescription: 'The total number of indexed nodes that should not be indexed according to the current Full Text Search config',
        couldntGetIncorrectIndexedNodes: "Couldn't get incorrectly indexed nodes",
        nodesAreIncorrectlyIndexed: '{0} node(s) are incorrectly indexed with full text content',
        reindexNode: 'Reindex Node',
        reindexNodes: 'Reindex Nodes',
        reindexedNodes: 'Reindexed {0} node(s)',
        reindexing: 'Reindexing...',
        reindex: 'Reindex',
        reindexDescription: 'Select whether or not to reindex all nodes',
        reindexWithDescendants: 'Reindex with descendants',
        includeDescendants: 'Include descendants',
        allNodes: 'All nodes',
        selectNodes: 'Select nodes',
        selectNodesDescription: 'Select the nodes to reindex',
        selectedNodes: 'Selected nodes',
        description: 'Description',
        developedBy: 'Developed by',
        sponsoredBy: 'Sponsored by',
        status: 'Status',
        search: 'Search',
        enterKeywordsHere: 'Enter keywords here',
        advancedSettings: 'Advanced settings',
        inspect: 'Inspect',
        searchType: 'Search type',
        searchTypeDescription: 'The type of search to perform.',
        titleProperties: 'Title properties',
        titlePropertiesDescription: 'Adds field names to use for title properties. Note, that this overrides the config setting, so you need to add all wanted fields for titles here.',
        titleBoost: 'Title boost',
        titleBoostDescription: 'Set the boosting value for the title properties, to make titles more important than body text when searching.',
        bodyProperties: 'Body properties',
        bodyPropertiesDescription: 'Adds field names to use for body properties. Note, that this overrides the config setting, so you need to add all wanted fields for bodytext here.',
        summaryProperties: 'Summary properties',
        summaryPropertiesDescription: "Adds field names to use for summary properties. Note, that if you don't specify any summary properties, the body properties will be used instead.",
        summaryLength: 'Summary length',
        summaryLengthDescription: 'Sets the summary length in the results. The default is 300 characters.',
        rootNodes: 'Root nodes',
        rootNodesDescription: 'With this setting, you can limit search results to be descendants of the selected nodes.',
        culture: 'Culture',
        cultureDescription: 'This is used to define which culture to search in. You should probably always set this, but it might work without it, in invariant sites.',
        enableWildcards: 'Enable wildcards',
        enableWildcardsDescription: 'This enables or disables use of wildcards in the search terms. Wildcard characters are added automatically to each of the terms.',
        fuzzyness: 'Fuzzyness',
        fuzzynessDescription: 'Fuzzyness is used to match your search term with similar words. This method sets the fuzzyness parameter of the search. The default is 0.8. If wildcards is enabled, fuzzyness will not be used.',
        allowedContentTypes: 'Allowed Content Types',
        allowedContentTypesDescription: 'Limit the search to nodes of the specified Content Type Aliases.',
        fullTextSearchIsDisabled: 'FullTextSearch is disabled',
        fullTextSearchIsEnabled: 'FullTextSearch is enabled',
        externalIndexNotFound: 'ExternalIndex not found',
        enabled: 'Enabled',
        defaultTitleField: 'Default Title field',
        indexingActiveKey: '"Indexing Active" key',
        disallowedContentTypeAliases: 'Disallowed Content Type aliases',
        disallowedPropertyAliases: 'Disallowed property aliases',
        xPathsToRemove: 'XPaths to remove from content',
        fullTextContentField: 'Full Text Content field',
        fullTextPathField: 'Full Text Path field'
    }
};
