export default {
    fullTextSearch: {
        indexStatus: "Statut de l'Index",
        indexableNodes: "Noeuds Indexables",
        indexableNodesDescription: "Le nombre total de noeuds indexables, selon la configuration actuelle du Full Text Search",
        allIndexableNodesAreIndexed: "Tous les noeuds indexables ont leur contenu intégral dans l'index",
        indexedNodes: "Noeuds Indexés",
        indexedNodesDescription: "Le nombre total de noeuds indexés qui peuvent être cherchés par le Full Text Search",
        missingNodes: "Noeuds manquant",
        missingNodesDescription: "Le nombre total de noeuds indexés manquant, selon la configuration actuelle du Full Text Search",
        couldntGetMissingNodes: "Impossible de récupérer les noeuds manquant",
        nodesAreMissingInIndex: "{0} noeud(s) n'ont pas leur contenu intégral dans l'index",
        incorrectIndexedNodes: "Noeuds Indexés Incorrectement",
        incorrectIndexedNodesDescription: "Le nombre total de noeuds indexés qui ne devraient pas l'être selon la configuration actuelle du Full Text Search",
        couldntGetIncorrectIndexedNodes: "Impossible de récupérer les noeuds indexés incorrectement",
        nodesAreIncorrectlyIndexed: "{0} noeud(s) sont incorrectement indexés avec leur contenu intégral",
        reindexNodes: "Indexer à nouveau les noeuds",
        reindexedNodes: "{0} noeud(s) ont été indexés à nouveau",
        reindexing: "Nouvelle indexation en cours...",
        reindex: "Indexer à nouveau",
        reindexDescription: "Choisissez s'il faut ou pas indexer à nouveau tous les noeuds",
        reindexWithDescendants: "Indexer à nouveau, y compris les descendants",
        includeDescendants: "Inclure les descendants",
        allNodes: "Tous les noeuds",
        selectNodes: "Sélectionner les noeuds",
        selectNodesDescription: "Sélectionner les noeuds à indexer à nouveau",
        selectedNodes: "Noeuds sélectionnés",
        description: "Description",
        developedBy: "Developpé par",
        sponsoredBy: "Sponsorisé par",
        status: "Statut",
        search: "Chercher",
        enterKeywordsHere: "Introduire les mots-clés ici",
        advancedSettings: "Réglages avancés",
        inspect: "Inspecter",
        searchType: "Type de recherche",
        searchTypeDescription: "Le type de recherche à exécuter.",
        titleProperties: "Propriétés pour le Titre",
        titlePropertiesDescription: "Ajouter le nom des champs à utiliser pour les propriété du titre. Notez que ceci remplace le paramètre de configuration, vous devez donc ajouter ici tous les champs souhaités pour le titre.",
        titleBoost: "Mise en avant du titre",
        titleBoostDescription: "Définissez la valeur de mise en avant pour les propriétés du titre, afin de rendre les titres plus importants que le corps du texte lors de la recherche.",
        bodyProperties: "Propriétés du Corps",
        bodyPropertiesDescription: "Ajouter le nom des champs à utiliser pour les propriétés du corps. Notez que ceci remplace le paramètre de configuration, vous devez donc ajouter ici tous les champs souhaités pour le corps du texte.",
        summaryProperties: "Propriétés du Résumé",
        summaryPropertiesDescription: "Ajouter le nom des champs à utiliser pour les propriétés du résumé. Notez que si vous ne spécifiez aucune propriété du résumé, les propriétés du corps seront utilisées à la place.",
        summaryLength: "Longueur du résumé",
        summaryLengthDescription: "Fixe la longueur du résumé dans les résultats. La valeur par défaut est de 300 caractères.",
        rootNodes: "Noeuds racine",
        rootNodesDescription: "Avec ce réglage, vous pouvez limiter les résultats de recherche aux descendants des noeuds sélectionnés.",
        culture: "Culture",
        cultureDescription: "Ceci est utilisé pour définir la culture dans laquelle la recherche est faite. Vous devriez probablement toujours la spécifier, mais cela pourrait fonctionner sans, notamment dans les sites invariants.",
        enableWildcards: "Activer les caractères génériques",
        enableWildcardsDescription: "Ceci active ou désactive l'utilisation de caractères génériques (wildcards) dans les termes de recherches. Les caractères génériques sont ajoutés automatiquement à chacun des termes.",
        fuzzyness: "Approximation",
        fuzzynessDescription: "L'approximation est utilisée pour faire correspondre votre terme de recherche avec des mots similaires. Cette méthode fixe le niveau d'approximation de la recherche. La valeur par défaut est 0,8. Si les caractères génériques sont activés, l'approximation ne sera pas utilisée.",
        allowedContentTypes: "Types de Contenu Autorisés",
        allowedContentTypesDescription: "Limite la recherche aux noeuds des Types de Contenu spécifiés.",
        fullTextSearchIsDisabled: "FullTextSearch est désactivé",
        fullTextSearchIsEnabled: "FullTextSearch est activé",
        externalIndexNotFound: "ExternalIndex n'a pas été trouvé",
        enabled: "Activé",
        defaultTitleField: "Champ par défaut pour le Titre",
        indexingActiveKey: 'Clé "Indexation Active"',
        disallowedContentTypeAliases: "Alias des Types de Contenu non-autorisés",
        disallowedPropertyAliases: "Alias des propriétés non-autorisées",
        xPathsToRemove: "XPaths à supprimer du contenu",
        fullTextContentField: "Champ du Contenu de Texte Intégral",
        fullTextPathField: "Champ du Chemin vers le Contenu Intégral"
    }
};
