export default {
    fullTextSearch: {
        indexStatus: "Indeksstatus",
        indexableNodes: "Indekserbare noder",
        indexableNodesDescription: "Det totale antall indekserbare noder, i henhold til gjeldende Full Text Search konfigurasjon",
        allIndexableNodesAreIndexed: "Alle indekserbare noder har fulltekstinnhold i indeksen",
        indexedNodes: "Indekserte noder",
        indexedNodesDescription: "Det totale antall indekserte noder som kan søkes etter av Full Text Search",
        missingNodes: "Manglende noder",
        missingNodesDescription: "Totalt antall manglende indekserte noder, i henhold til gjeldende Full Text Search konfigurasjon",
        couldntGetMissingNodes: "Kunne ikke hente manglende noder",
        nodesAreMissingInIndex: "{0} node(r) mangler fulltekstinnhold i indeksen",
        incorrectIndexedNodes: "Feilaktig indekserte noder",
        incorrectIndexedNodesDescription: "Det totale antall indekserte noder som ikke skal indekseres i henhold til gjeldende Full Text Search-konfigurasjon",
        couldntGetIncorrectIndexedNodes: "Kunne ikke hente feilaktig indekserte noder",
        nodesAreIncorrectlyIndexed: "{0} node(r) er feilaktig indeksert med fulltekstinnhold",
        reindexNodes: "Reindekser noder",
        reindexedNodes: "Reindekserte {0} node(r)",
        reindexing: "Reindekserer...",
        reindex: "Reindekser",
        reindexDescription: "Velg om alle noder skal reindekseres",
        reindexWithDescendants: "Reindekser med etterkommere",
        includeDescendants: "Inkluder etterkommere",
        allNodes: "Alle noder",
        selectNodes: "Velg noder",
        selectNodesDescription: "Velg nodene som skal reindekseres",
        selectedNodes: "Valgte noder",
        description: "Beskrivelse",
        developedBy: "Utviklet av",
        sponsoredBy: "Sponset av",
        status: "Status",
        search: "Søk",
        enterKeywordsHere: "Skriv inn nøkkelord her",
        advancedSettings: "Avanserte innstillinger",
        inspect: "Inspiser",
        searchType: "Søketype",
        searchTypeDescription: "Typen søk du vil utføre.",
        titleProperties: "Tittelegenskaper",
        titlePropertiesDescription: "Legger til feltnavn som brukes for tittelegenskaper. Merk at dette overstyrer innstillingene, så du må legge til alle ønskede felt for titler her.",
        titleBoost: "Tittelboost",
        titleBoostDescription: "Still inn boostingsverdien for tittelegenskapene for å gjøre titler viktigere enn brødtekst når du søker.",
        bodyProperties: "Brødtekstegenskaper",
        bodyPropertiesDescription: "Legger til feltnavn som brukes for brødtekstegenskaper. Merk at dette overstyrer innstillingene, så du må legge til alle ønskede felt for brødtekst her.",
        summaryProperties: "Oppsummeringsegenskaper",
        summaryPropertiesDescription: "Legger til feltnavn som skal brukes for oppsummeringsegenskaper. Merk at hvis du ikke spesifiserer noen oppsummeringsegenskaper, vil brødtekstegenskapene brukes i stedet.",
        summaryLength: "Oppsummeringslengde",
        summaryLengthDescription: "Angir sammendragets lengde i resultatene. Standardverdien er 300 tegn.",
        rootNodes: "Hovednoder",
        rootNodesDescription: "Med denne innstillingen kan du begrense søkeresultatene til å være etterkommere av de valgte nodene.",
        culture: "Kultur",
        cultureDescription: "Dette brukes til å definere hvilken kultur du skal søke i. Du bør sannsynligvis alltid angi dette, men det kan fungere uten den, på uforanderlige nettsteder.",
        enableWildcards: "Aktiver jokertegn",
        enableWildcardsDescription: "Disse aktiverer eller deaktiverer bruk av jokertegn i søkeordene. Jokertegn blir automatisk lagt til hvert av søkeordene.",
        fuzzyness: "Fuzzyness",
        fuzzynessDescription: "Fuzzyness brukes til å matche søkeordet ditt med lignende ord. Denne metoden angir fuzzyness-parameteren for søket. Standard er 0,8. Hvis jokertegn er aktivert, vil ikke fuzzyness brukes.",
        fullTextSearchIsDisabled: "FullTextSearch er deaktivert",
        externalIndexNotFound: "ExternalIndex ikke funnet"
    }
};
